config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'cookys',             to: 'pages#cookys',               as: :cookys
  get 'mentions',           to: 'pages#mentions',             as: :mentions
  get 'confidentialites',   to: 'pages#confidentialites',     as: :confidentialites
  get 'faq',   to: 'pages#faq',     as: :faq

  get "/404", to: "errors#not_found", via: :all
  get "/422", to: "errors#unacceptable", via: :all
  get "/500", to: "errors#internal_server_error", via: :all

  resources :services, only: [ :new, :create, :index, :show ] do
    resources :activities, only: [ :new, :create ]
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :service
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_one_attached :logo
  has_one_attached :image
  has_many :activities, dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @service = Service.find(params[:service_id])
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @service = Service.find(params[:service_id])
    @activity.service = @service
    if @activity.save
      redirect_to service_path(@service)
    else
      render :new
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:sample)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render status: 404
  end

  def unacceptable
    render status: 422
  end

  def internal_server_error
    render status: 500
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @services = Service.all.sort
  end

  def cookys
  end

  def mentions
  end

  def confidentialites
  end

  def faq
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index

  end

  def show
    @service = Service.friendly.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.save

    redirect_to service_path(service)
  end

  private

  def service_params
    params.require(:service).permit(:name, :fullname, :logo, :image, :definition, :option, :presample, :conditions, :plafond)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/activities/new.html.erb
<%= simple_form_for [ @service, @activity ] do |f| %>
  <%= f.input :sample %>
  <%= f.submit "Submit Activity", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Les Services de Benoit | Service à la Personne</title>
    <meta name="description" content="#{meta_description}">

    <!-- Google / Search Engine Tags -->
    <meta itemprop="name" content="#{meta_title}" >
    <meta itemprop="description" content="#{meta_description}">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="#{meta_title}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="#{request.original_url}">
    <meta property="og:image" content="#{meta_image}">
    <meta property="og:description" content="#{meta_description}">
    <meta property="og:site_name" content="#{meta_title}">

    <%= favicon_link_tag 'favbellicon.webp' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Poppins:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/confidentialites.html.erb
<div class="container container-legales">
  <div class="legales-section">
    <div class="legales-title text-center">
      <h2>DONNÉES PERSONNELLES</h2>
    </div>
    <div class="legales-content text-justify">
      <p>
        Politique de Confidentialité & Protection des données personnelles appliquées par Les Services de Benoit
      </p>
      <br>
      <h4>1 - Description</h4>
      <p>
        Les Services de Benoit est un site vitrine destiné: <br>
        * aux Particuliers à la recherche de prestations de services à domicile en priorité, mais aussi à leurs proches aidants, <br>
        * aux Partenaires (entreprises, institutions publiques, associations, particuliers) et potentiels partenaires des Services de Benoit. <br>
        La finalité du site www.servicesdebenoit.com est de fournir une information claire et sincère quant à l’ensemble des activités des Services de Benoit.
      </p>
      <h4>2 - Responsable du traitement des données</h4>
      <p>
        Benoit Bessiere <br>
        e-mail : benoit@servicesdebenoit.com  <br>
        Adresse : 42 chemin de la planche brûlée - 01210 Ferney-Voltaire. <br>
        tél : 09 72 53 28 80
      </p>
      <h4>3 - Méthodes de collecte des données personnelles</h4>
      <p>
        Au cours de votre visite sur le site www.servicesdebenoit.com, des données personnelles vous concernant pourront être recueillies ou traitées par Les Services de Benoit.
      </p>
      <h4>Formulaire de Contact</h4>
      <p>
        En cas de demande de contact, vous serez invité(e) à remplir un formulaire dont les informations collectées sont uniquement destinées à nous permettre de mieux répondre à votre demande.
      </p>
      <h4>Cookies</h4>
      <p>
        Au cours de votre visite sur notre site www.servicesdebenoit.com, Il est possible que nous déposions sur votre ordinateur un « cookie ». Un cookie est un petit bout de code envoyé par un serveur Internet qui s'enregistre sur votre ordinateur; il permet de garder la trace du site Internet que vous avez visité, et contient un certain nombre de données sur cette visite. <br>
        Les cookies nous permettent notamment: <br>
        - de favoriser l’amélioration générale et l’ergonomie de notre site, de reconnaître votre appareil lors de chacune de vos visites sur le site www.servicesdebenoit.com afin de faciliter votre expérience utilisateur, <br>
        - de filtrer les robots, techniques de fraude et autres scripts malicieux générant du trafic illégitime sur les contenus disponibles sur le site. <br>
        Pour rappel, la plupart des navigateurs permettent de supprimer ou désactiver les cookies si vous le désirez. Ces options se trouvent généralement dans les préférences, paramètres ou autres menus de confidentialité de votre navigateur Internet.
      </p>
      <h4>4 - Informations collectées</h4>
      <p>
        Les informations collectées sont les suivantes: <br>
        - Données générales et techniques propres à votre visite sur le site (source de trafic, système d’exploitation, navigateur et type d’équipement utilisé, pays et ville de connexion via votre adresse IP, institution via laquelle vous accédez à nos services, etc.), <br>
        - Toute information que vous nous avez donnée volontairement, en remplissant notre formulaire de contact.
      </p>
      <p>
        Outre les finalités reprises au paragraphe concernant les cookies, les données vous concernant sont recueillies et traitées aux seules fins mentionnées ci-dessous: <br>
        - Etablissement de devis personnalisé répondant aux besoins exprimés dans le formulaire de contact. <br>
        - Réalisation de statistiques à destination de notre société. <br>
        La technologie évoluant chaque jour, Les Services de Benoit pourrait être amené à effectuer des traitements qui ne sont pas encore prévus dans cette Charte Vie Privée. Dans ce cas, nous vous contacterons avant de réutiliser vos données, afin de vous faire connaître les changements du règlement et vous donner la possibilité, le cas échéant, de refuser cette réutilisation.
      </p>
      <h4>5 - Consentement</h4>
      <p>
        En utilisant notre site www.servicesdebenoit.com,  vous déclarez explicitement accepter la politique de respect de la vie privée des Services de Benoit, et vous consentez à ce que nous recueillons et traitons les données vous concernant selon les modalités et principes décrits dans cette charte.
      </p>
      <h4>6 - Transmission aux tiers</h4>
      <p>
        Vos données ne seront transmises à aucun tiers sans votre consentement. <br>
        Toutefois, nous nous réservons le droit de divulguer des informations personnelles sur requête d'une autorité légale ou en toute bonne foi en considérant que cette action est requise: <br>
        - Pour se conformer à toute loi ou réglementation en vigueur, <br>
        - Pour protéger ou défendre les droits ou les biens des Services de Benoit, du site www.servicesdebenoit.com ou des utilisateurs de ce dernier, <br>
        - Pour intervenir, dans des circonstances extrêmes, dans le but de protéger la sécurité personnelle des utilisateurs des Services de Benoit, du site ou du public.
      </p>
      <h4>7 - Droit d'accès et de rectification</h4>
      <p>
        Conformément au Droit Français en matière de protection des données, il vous est toujours possible de nous contacter afin de vérifier l’état des données vous concernant. Nous vous les communiquerons dans les meilleurs délais, après un contrôle de votre identité. <br>
        En cas de données erronées, inexactes ou incomplètes, vous pourrez évidemment nous demander de rectifier ces informations. De même, si vous estimez que notre site ne respecte pas la réglementation sur la protection de la vie privée, vous pouvez nous contacter.
      </p>
      <h4>8 - Sécurité</h4>
      <p>
        Les services de Benoit s'engage à faire le maximum d’efforts pour protéger vos données à caractère personnel, afin notamment d'empêcher qu'elles soient déformées, endommagées ou communiquées à des tiers non autorisés.
      </p>
      <h4>9 - RGPD</h4>
      <p>
        Les services de Benoit s’engage à respecter le Règlement Général sur la Protection des Données et s'investit dans une démarche globale de mise en conformité RGPD soutenue par Les Services de Benoit.
      </p>
    </div>
    <div class="legales-link-return text-center">
      <%= link_to 'RETOUR', root_path, class:'btn-return' %>
    </div>
  </div>
</div>

app/views/pages/cookys.html.erb
<div class="container container-legales">
  <div class="legales-section">
    <div class="legales-title text-center">
      <h2>COOKIES</h2>
    </div>
    <div class="legales-content text-justify">
      <p>
        Cette politique de cookies a été mise à jour pour la dernière fois le 29 octobre 2020 et s’applique aux citoyens de l’Espace Économique Européen.
      </p>
      <h4>1. Introduction</h4>
      <p>
        Notre site web, https://www.servicesdebenoit.com (ci-après : « le site web ») utilise des cookies et autres technologies liées (par simplification, toutes ces technologies sont désignées par le terme « cookies »). Des cookies sont également placés par des tierces parties que nous avons engagées. Dans le document ci-dessous, nous vous informons de l’utilisation des cookies sur notre site web.
      </p>
      <h4>2. Que sont les cookies ?</h4>
      <p>
        Un cookie est un petit fichier simple envoyé avec les pages de ce site web et stocké par votre navigateur sur le disque dur de votre ordinateur ou d’un autre appareil. Les informations qui y sont stockées peuvent être renvoyées à nos serveurs ou aux serveurs des tierces parties concernées lors d’une visite ultérieure.
      </p>
      <h4>3. Que sont les scripts ?</h4>
      <p>
        Un script est un élément de code utilisé pour que notre site web fonctionne correctement et de manière interactive. Ce code est exécuté sur notre serveur ou sur votre appareil.
      </p>
      <h4>4. Qu’est-ce qu’une balise invisible ?</h4>
      <p>
        Une balise invisible (ou balise web) est un petit morceau de texte ou d’image invisible sur un site web, utilisé pour suivre le trafic sur un site web. Pour ce faire, diverses données vous concernant sont stockées à l’aide de balises invisibles.
      </p>
      <h4>5. Cookies</h4>
      <h5>5.1 Cookies techniques ou fonctionnels</h4>
      <p>
        Certains cookies assurent le fonctionnement correct de certaines parties du site web et la prise en compte de vos préférences en tant qu’utilisateur. En plaçant des cookies fonctionnels, nous vous facilitons la visite de notre site web. Ainsi, vous n’avez pas besoin de saisir à plusieurs reprises les mêmes informations lors de la visite de notre site web et, par exemple, les éléments restent dans votre panier jusqu’à votre paiement. Nous pouvons placer ces cookies sans votre consentement.
      </p>
      <h5> 5.2 Cookies analytiques</h4>
      <p>
        Les statistiques sont suivies de façon anonyme, aucune permission n’est donc demandée pour placer des cookies analytiques.
      </p>
      <h4>6. Cookies placés</h4>
      <p>
        Cookie Notice for RGDP <br>
        Divers
      </p>
      <h4>7. Consentement</h4>
      <p>
        Lorsque vous visitez notre site web pour la première fois, nous vous montrerons une fenêtre contextuelle avec une explication sur les cookies. Dès que vous cliquez sur « Enregistrer les préférences » vous nous autorisez à utiliser les catégories de cookies et d’extensions que vous avez sélectionnés dans la fenêtre contextuelle, comme décrit dans la présente politique de cookies. Vous pouvez désactiver l’utilisation des cookies via votre navigateur, mais veuillez noter que notre site web pourrait ne plus fonctionner correctement.
      </p>
      <h5>7.1 Gérez vos réglages de consentement</h4>
      <p>Fonctionnels</p>
      <h4>8. Vos droits concernant les données personnelles</h4>
      <p>
        Vous avez les droits suivants concernant vos données personnelles: <br>
        Vous avez le droit de savoir pourquoi vos données personnelles sont nécessaires, ce qui leur arrivera et combien de temps elles seront conservées. <br>
        Droit d’accès: vous avez le droit d’accéder à vos données personnelles que nous connaissons.
        Droit de rectification : vous avez le droit à tout moment de compléter, corriger, faire supprimer ou bloquer vos données personnelles. <br>
        Si vous nous donnez votre consentement pour le traitement de vos données, vous avez le droit de révoquer ce consentement et de faire supprimer vos données personnelles. <br>
        Droit de transférer vos données: vous avez le droit de demander toutes vos données personnelles au responsable du traitement et de les transférer dans leur intégralité à un autre responsable du traitement. <br>
        Droit d’opposition: vous pouvez vous opposer au traitement de vos données. Nous obtempérerons, à moins que certaines raisons ne justifient ce traitement. <br>
        Pour exercer ces droits, veuillez nous contacter. Veuillez vous référer aux coordonnées au bas de cette politique de cookies. Si vous avez une plainte concernant la façon dont nous traitons vos données, nous aimerions en être informés, mais vous avez également le droit de déposer une plainte auprès de l’autorité de contrôle (l’autorité chargée de la protection des données, comme le CEPD).
      </p>
      <h4>9. Activer/désactiver et supprimer les cookies</h4>
      <p>
        Vous pouvez utiliser votre navigateur internet pour supprimer automatiquement ou manuellement les cookies. Vous pouvez également spécifier que certains cookies ne peuvent pas être placés. Une autre option consiste à modifier les réglages de votre navigateur internet afin que vous receviez un message à chaque fois qu’un cookie est placé. Pour plus d’informations sur ces options, reportez-vous aux instructions de la section Aide de votre navigateur.
      </p>
      <p>
        Veuillez noter que notre site web peut ne pas marcher correctement si tous les cookies sont désactivés. Si vous supprimez les cookies dans votre navigateur, ils seront de nouveau placés après votre consentement lorsque vous revisiterez nos sites web.
      </p>
      <h4>10. Coordonnées</h4>
      <p>Pour des questions et/ou des commentaires sur notre politique en matière de cookies et cette déclaration, veuillez nous contacter en utilisant les coordonnées suivantes:</p>
      <br>
      <p>
        Benoit Bessiere <br>
        Site web: https://www.servicesdebenoit.com <br>
        E-mail: benoit@servicesdebenoit.com
      </p>
    </div>
    <div class="legales-link-return text-center">
      <%= link_to 'RETOUR', root_path, class:'btn-return' %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="section-home">
  <div class="home">
    <div class="home-body">
      <h1>LES SERVICES DE BENOIT</h1>
      <%= image_tag 'bell-orange.webp', id:"bell" %>
      <div class="home-body-text" data-aos="zoom-in-up" data-aos-delay="2000">
        <p>Aide à la personne<br>Prestations à domicile<br>sur mesure</p>
      </div>
    </div>
    <div class="home-footer">
      <%= image_tag 'sap-b&w.svg', id:"sap", alt: "Logo SAP", height:"70px", width:"auto" %>
      <%= image_tag 'pays-de-gex.webp', id:"paysdegex", alt: "logo du Pays de Gex", height:"50px", width:"auto" %>
    </div>
  </div>
</div>
<div class="section-services" id="services">
  <div class="title-section title-services" data-aos="zoom-in-down" >
    <h2>SERVICES PROPOSÉS</h2>
  </div>
  <div class="subtitle text-center">
    <p>Vous n'avez pas le temps, l'envie ou la patience pour certaines tâches de la vie quotidienne. </p>
    <span id="ben">Benoît est à votre service !</span>
  </div>
  <div class="services-wrapper">
    <% @services.each do |service|%>
      <%= link_to service_path(service), class:'service-card-link' do %>
        <div class="service-card">
          <div class="service-icone">
            <%= cl_image_tag service.logo.key, height: 50 %>
          </div>
          <div class="service-name">
            <h4><%= service.name %></h4>
          </div>
          <p>En savoir +</p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="section-coronavirus" id="coronavirus" >
  <div class="coronavirus">
    <div class="title-section title-coronavirus" data-aos="zoom-in-down">
      <h2>SPECIAL covid-19</h2>
    </div>
    <div class="coronavirus-text" data-aos="zoom-out">
      <p>Des mesures de protection ont été mises en place permettant des prestations à domicile dans le respect des règles d'hygiène préconisées par l'Etat et notamment des gestes barrières.</p>
    </div>
  </div>
</div>
<div class="section-info" id="info">
  <div class="title-section title-sap" data-aos="zoom-in-down" >
    <h2>SERVICE A LA PERSONNE / SAP</h2>
  </div>
  <div class="info-wrapper">
    <div class="info-box">
      <div class="info-box-title">
        <div class="corner"></div>
        <div class="cornerbis"></div>
        <div class="title-wrapper">
          <h3>LES AVANTAGES</h3>
        </div>
      </div>
      <div class="info-box-img">
        <%= image_tag 'logo_sap.svg', alt:"logo service à la personne", loading:"lazy", width:280, height:131 %>
      </div>
      <div class="info-text">
        <p>
          En faisant appel aux Services de Benoît, Les dépenses que vous engagez à ce titre vous donnent droit à un crédit d’impôt de 50%, dans la limite des plafonds autorisés. <br>
          Jusqu’à présent, vous bénéficiiez de votre crédit d’impôt l’année suivant les dépenses, au moment de votre déclaration auprès de l’administration fiscale…
        </p>
      </div>
    </div>
    <div class="info-box">
      <div class="info-box-title">
        <div class="corner"></div>
        <div class="cornerbis"></div>
        <div class="title-wrapper">
          <h3>L'AVANCE IMMÉDIATE</h3>
        </div>
      </div>
      <div class="info-box-img">
        <%= image_tag 'urssaf-AI.webp', alt:"avance immédiate URSSAF", loading:"lazy", width:280, height:131 %>
      </div>
      <div class="info-text">
        <p>
          Ce service vous est proposé par l’URSSAF. Il est optionnel et gratuit.  Il vous permet ainsi de bénéficier en temps réel de votre avantage fiscale de 50% lors du paiement de votre facture. <br>
          Pour en profiter, il vous suffit simplement de demander à votre prestataire de services préféré, Benoît, de vous y inscrire.
        </p>
        <%= link_to '+ de détails sur Avance Immédiate', faq_path, class:"faq-link" %>
      </div>
    </div>
    <div class="info-box">
      <div class="info-box-title">
        <div class="corner"></div>
        <div class="cornerbis"></div>
        <div class="title-wrapper">
          <h3>DÉCLARATION FISCALE</h3>
        </div>
      </div>
      <div class="info-box-img">
        <%= image_tag 'impots.webp', alt:"Fiche de déclaration d'impôts", loading:"lazy", width:280, height:131 %>
      </div>
      <div class="info-text">
        <p>
          Au mois de janvier, vous recevrez une attestation fiscale reprenant la nature des prestations fournies, les sommes réglées pour l'année précédente. Cette attestation et les factures reçues seront à conserver précieusement comme justificatifs pour votre déclaration de revenus.
        </p>
      </div>
    </div>
    <div class="info-box">
      <div class="info-box-title">
        <div class="corner"></div>
        <div class="cornerbis"></div>
        <div class="title-wrapper">
          <h3>TARIFS & DEVIS</h3>
        </div>
      </div>
      <div class="info-box-img">
        <%= image_tag 'logo_bell.webp', alt:"Logo Services de Benoit", loading:"lazy", width:280, height:131 %>
      </div>
      <div class="info-text">
        <p>
          Les tarifs varient selon la prestation de service demandée et la fréquence d’intervention. <br>
          Un devis gratuit personnalisé vous sera remis pour toute prestation ou ensemble de prestations dont le prix total est supérieur ou égal à 100 €, ou sur demande si le prix est inférieur.
        </p>
      </div>
    </div>
    <div class="text-center text-muted" id="declaration">
      Les Services de Benoît font l'objet d'une déclaration auprès de l'Organisme des Services à la Personne n°: SAP751342247
    </div>
  </div>
</div>
<div class="section-apropos" id="apropos">
  <div class="apropos">
    <div class="title-section title-apropos">
      <h2>À PROPOS DE BENOÎT</h2>
    </div>
    <%= image_tag 'pola-portrait.webp', alt:"portrait", loading:"lazy", width:"400px", height:"439px" %>
    <div class="profile" data-aos="zoom-out">
      <p>Plus de 20 années d'expérience, à l'écoute et au service d'une clientèle française et internationale à la réception d'hôtels et dans les services aux expatriés.</p>
    </div>
  </div>
</div>
<div class="section-contact" id="contact">
  <div class="title-section title-contact" data-aos="zoom-in-down">
    <h2>CONTACTER MOI</h2>
  </div>
  <div class="form-wrapper">
    <div class="contact-infos">
      <div class="phone" data-aos="fade-right" data-aos-delay="400">
        <%= image_tag 'phone-orange.svg', alt:"icon phone", height:16, width:12, loading:"lazy" %>
        09.72.53.28.80
      </div>
      <div class="mail" data-aos="fade-left" data-aos-delay="600">
        <%= image_tag 'envelop-orange.svg', alt:"icon envelop", height:16, width:22, loading:"lazy" %>
        benoit@servicesdebenoit.com
      </div>
    </div>
    <form action="https://formspree.io/xeqrpboq" method="POST" >
      <input type="text" name="name" id="full-name" autocomplete="off" required placeholder="Nom" />
      <input type="email" name="_replyto" autocomplete="off" required placeholder="Email"/>
      <input type="phone" name="phone" autocomplete="off" required placeholder="Téléphone"/>
      <textarea row="3" name="message" id="message" required placeholder="Message..."></textarea>
      <input type="hidden" name="_subject" id="email-subject" value="Formulaire SAP">
      <input type="submit" value="ENVOYER" class="btn-contact">
    </form>
  </div>
</div>

app/views/services/new.html.erb
<div class="container-service">
  <h1>Register a new service</h1>
  <div class="wrap-service-form">
    <%= simple_form_for(restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :fullname %>
      <%= f.input :logo, as: :file %>
      <%= f.input :image, as: :file %>
      <%= f.input :definition %>
      <%= f.input :option %>
      <%= f.input :presample %>
      <%= f.input :conditions %>
      <%= f.input :plafond %>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-header">
    <h2>LES SERVICES DE BENOIT</h2>
    <%= image_tag 'footer-bell.webp', alt:"footer-logo", loading:"lazy", width:200, height:200 %>
  </div>
   <div class="footer-body">
      <%= image_tag 'sap-b&w.svg', id:"sap", alt:"footer logo sap", loading:"lazy", height:70, width:85 %>
      <%= image_tag 'pays-de-gex.webp', id:"paysdegex", alt:"footer logo pdg", loading:"lazy", height:40, width:172 %>
    </div>
  <div class="footer-links">
    <div class="footer-mentions">
      <p>LIENS UTILES :</p>
      <hr class="tiret">
      <%= link_to 'Avance Immédiate', faq_path %>
      <%= link_to 'Cookies', cookys_path %>
      <%= link_to 'Mentions Légales', mentions_path %>
      <%= link_to 'Politique de Confidentialité', confidentialites_path %>
    </div>
    <div class="footer-sap">
      <p>LES SERVICES DE BENOIT :</p>
      <hr class="tiret">
      <%= link_to 'Assistance Administrative', service_path(11) %>
      <%= link_to 'Assistance Informatique', service_path(12) %>
      <%= link_to 'Petit Bricolage', service_path(13) %>
      <%= link_to 'Courses & Livraisons', service_path(14)  %>
      <%= link_to 'Vigilance du Domicile', service_path(15) %>
    </div>
    <div class="footer-contact">
      <p>CONTACT</p>
      <hr class="tiret">
      <div class="footer-contact-details">
        <%= image_tag 'phone-gray.svg', alt:"footer icon phone", height:16, width:12, loading:"lazy" %>
        <p>09 72 53 28 80</p>
      </div>
      <br>
      <div class="footer-contact-details">
        <%= image_tag 'envelop-gray.svg', alt:"footer icon envelop", height:16, width:22, loading:"lazy" %>
        <p>benoit@servicesdebenoit.com</p>
      </div>
    </div>
    <div class="footer-social">
      <p>RÉSEAUX SOCIAUX</p>
      <hr class="tiret">
      <div class="footer-social-icons">
        <%= link_to "http://www.facebook.com/mypage", target: :_blank do %>
          <%= image_tag 'facebook-gray.svg', alt:"icon Facebook", loading:"lazy", height:32, width:32 %>
        <% end %>
        <%= link_to "http://www.instagram.com/mypage", target: :_blank do %>
          <%= image_tag 'instagram-gray.svg', alt:"icon Instagram", loading:"lazy", height:32, width:32 %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="copyright text-center">
    © Les Services De Benoit 2023
  </div>
</div>